# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            ANG
tagline:          'The University of Liverpool Advanced Networks Group'
description:      'Advanced connectivity for advanced applications; Trusted Autonomy, High Speed CANs, Haptics, Secure Wireless'
url:              http://hyde.getpoole.com

author:
  name:           'ANG'
  url:            https://twitter.com/liv_ang

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/andrewbolster/advanced-networks-group
