# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            A.N.R.G.
tagline:          'The University of Liverpool Advanced Networks Research Group'
description:      'Advanced connectivity for advanced applications; Trusted Autonomy, High Speed CANs, Haptics, Secure Wireless'
logo:             /public/img/ang_logo.png
url:              http://andrewbolster.info/advanced-networks-group/
baseurl:          /advanced-networks-group

author:
  name:           'ANG'
  url:            https://twitter.com/liv_ang

paginate:         5
paginate_path:    "blog/page:num"

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/andrewbolster/advanced-networks-group
